parameters:
    locale: en
    locales: [en, fr]
    secret: 10784a86848b5412b5f7fa644e90ef24e
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: ~
    database_name: slidev
    database_user: slidev
    database_password: slidev
    database_path: null
    phpcr_backend:
        type: doctrinedbal
        connection: doctrine.dbal.default_connection
# Enable these lines to use file system caching for the storage API
#        caches:
#            meta: liip_doctrine_cache.ns.meta
#            nodes: liip_doctrine_cache.ns.nodes
    phpcr_workspace: default
    phpcr_user: admin
    phpcr_pass: admin
